security:
  basic:
    enabled: false # turn of securing our application endpoints

logging:
  level:
    io:
      pivotal: DEBUG

management:
  security:
    enabled: false # turn of securing the actuator endpoints

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
